# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-06 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_change_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='currency',
            field=models.CharField(default='ngn', help_text='Lower-case ISO currency codes', max_length=8),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='currency',
            field=models.CharField(default='ngn', help_text='Lower-case ISO currency codes', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='ngn', max_length=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='ngn', max_length=8),
        ),
    ]
